timeout: 0
quiet: yes

/Northport
protocol: limine
path: boot():/npk.elf
cmdline: npk.debugger.enable=yes; npk.debugger.auto_connect=no; npk.x86.com1_for_debugger=yes

#ifdef NPK_HAS_KASLR
kaslr: yes
#else
kaslr: no
#endif
