TARGET = Test

CXX_FLAGS = $(DRIVER_CXX_FLAGS) -Iinclude -I$(PROJ_ROOT_DIR)/kernel/include
LD_FLAGS = $(DRIVER_LD_FLAGS)

CXX_SRCS = Main.cpp

include $(PROJ_ROOT_DIR)/misc/BuildCommon.mk

all: $(TARGET_DRIVER)

