name: All-Platforms Builds

on:
  push:
    paths-ignore: [ 'docs/**' ]
  pull_request:
    paths-ignore: [ 'docs/**' ]

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest

    steps:
    - name: Check for Cached Binaries
      id: cached-compiler-binaries
      uses: actions/cache@v2
      with:
        path: |
          **/gcc-x86_64-cross
          **/gcc-riscv64-cross
          **/gcc-m68k-cross
        key: gcc-bins-2024-07-06

    - name: Download LLVM + Clang
      run: sudo apt install lld llvm

    - name: Download GCC for x86_64
      if: steps.cached-compiler-binaries.outputs.cache-hit != 'true'
      run: >
        mkdir toolchains;
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--stable-2022.08-1.tar.bz2 -O toolchains/gcc-x86_64;
        cd toolchains;
        tar -vxf gcc-x86_64; mv x86-64--glibc--stable-2022.08-1 gcc-x86_64-cross;
    
    - name: Download GCC for risc-v 64
      if: steps.cached-compiler-binaries.outputs.cache-hit != 'true'
      run: >
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/riscv64-lp64d/tarballs/riscv64-lp64d--glibc--stable-2022.08-1.tar.bz2 -O toolchains/gcc-riscv64;
        cd toolchains;
        tar -vxf gcc-riscv64; mv riscv64-lp64d--glibc--stable-2022.08-1 gcc-riscv64-cross

    - name: Download GCC for m68k
      if: steps.cached-compiler-binaries.outputs.cache-hit != 'true'
      run: >
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/m68k-68xxx/tarballs/m68k-68xxx--glibc--stable-2024.02-1.tar.bz2 -O toolchains/gcc-m68k;
        cd toolchains;
        tar -vxf gcc-m68k; mv m68k-* gcc-m68k-cross
    
    - uses: actions/checkout@v3
      with:
        path: 'repo'

    - name: Compile with GCC for m68k
      run: >
        cd repo;
        make clean;
        make binaries
        CPU_ARCH=m68k
        TOOLCHAIN=gcc
        X_CXX_BIN=$GITHUB_WORKSPACE/toolchains/gcc-m68k-cross/bin/m68k-buildroot-linux-gnu-g++
        X_AS_BIN=$GITHUB_WORKSPACE/toolchains/gcc-m68k-cross/bin/m68k-buildroot-linux-gnu-as
        X_LD_BIN=$GITHUB_WORKSPACE/toolchains/gcc-m68k-cross/bin/m68k-buildroot-linux-gnu-ld
        X_AR_BIN=$GITHUB_WORKSPACE/toolchains/gcc-m68k-cross/bin/m68k-buildroot-linux-gnu-ar

    - name: Compile with Clang for m68k
      if: false
      run: >
        cd repo;
        make clean;
        make binaries
        CPU_ARCH=m68k
        TOOLCHAIN=clang
    
    - name: Compile with GCC for x86_64
      run: >
        cd repo;
        make clean;
        make binaries 
        CPU_ARCH=x86_64
        TOOLCHAIN=gcc 
        X_CXX_BIN=$GITHUB_WORKSPACE/toolchains/gcc-x86_64-cross/bin/x86_64-buildroot-linux-gnu-g++
        X_AS_BIN=$GITHUB_WORKSPACE/toolchains/gcc-x86_64-cross/bin/x86_64-buildroot-linux-gnu-as
        X_LD_BIN=$GITHUB_WORKSPACE/toolchains/gcc-x86_64-cross/bin/x86_64-buildroot-linux-gnu-ld
        X_AR_BIN=$GITHUB_WORKSPACE/toolchains/gcc-x86_64-cross/bin/x86_64-buildroot-linux-gnu-ar

    - name: Compile with Clang for x86_64
      run: >
        cd repo;
        make clean;
        make binaries
        CPU_ARCH=x86_64
        TOOLCHAIN=clang
    
    - name: Compile with GCC for rv64
      run: >
        cd repo;
        make clean;
        make binaries 
        CPU_ARCH=riscv64
        TOOLCHAIN=gcc 
        TOOLCHAIN_PREFIX=../gcc-riscv64-cross
        X_CXX_BIN=$GITHUB_WORKSPACE/toolchains/gcc-riscv64-cross/bin/riscv64-buildroot-linux-gnu-g++
        X_AS_BIN=$GITHUB_WORKSPACE/toolchains/gcc-riscv64-cross/bin/riscv64-buildroot-linux-gnu-as
        X_LD_BIN=$GITHUB_WORKSPACE/toolchains/gcc-riscv64-cross/bin/riscv64-buildroot-linux-gnu-ld
        X_AR_BIN=$GITHUB_WORKSPACE/toolchains/gcc-riscv64-cross/bin/riscv64-buildroot-linux-gnu-ar
    
    - name: Compile with Clang for rv64
      run: >
        cd repo;
        make clean;
        make binaries
        CPU_ARCH=riscv64
        TOOLCHAIN=clang
