name: Build Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Download LLVM + Clang
      run: sudo apt install lld llvm

    - name: Download GCC for x86_64
      run: >
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--bleeding-edge-2021.11-5.tar.bz2 -O ../gcc-x86_64;
        cd ..;
        tar -vxf gcc-x86_64; mv x86-64--glibc--bleeding-edge-2021.11-5 gcc-x86_64-cross
    
    - name: Download GCC for risc-v 64
      run: >
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/riscv64--glibc--bleeding-edge-2021.11-5.tar.bz2 -O ../gcc-riscv64;
        cd ..;
        tar -vxf gcc-riscv64; mv riscv64--glibc--bleeding-edge-2021.11-5 gcc-riscv64-cross
    
    - uses: actions/checkout@v2

    - name: Compile with Clang for x86_64
      run: >
        make clean;
        make binaries CPU_ARCH=x86_64 TOOLCHAIN=clang
    
    - name: Compile with GCC for x86_64
      run: >
        make clean;
        make binaries 
        CPU_ARCH=x86_64
        TOOLCHAIN=gcc 
        TOOLCHAIN_PREFIX=../gcc-x86_64-cross
        X_CXX_BIN=x86_64-buildroot-linux-gnu-g++
        X_AS_BIN=x86_64-buildroot-linux-gnu-as
        X_LD_BIN=x86_64-buildroot-linux-gnu-ld
        X_AR_BIN=x86_64-buildroot-linux-gnu-ar

