name: Build and Publish Documentation

on:
  push:
    paths: [ 'docs/**', '.github/workflows/build-publish-docs.yml' ]
  pull_request:
    paths: [ 'docs/**', '.github/workflows/build-publish-docs.yml' ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Latex tools
      uses: teatimeguest/setup-texlive-action@v2.5.0
      with:
        packages: scheme-basic geometry parskip fontenc hyperref enumitem pgf titlesec fancyhdr etoolbox
    
    - uses: actions/checkout@v3

    - name: Compile Documentation
      run: make docs
    
    - name: Remove Previous Release
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Latest Tag
      uses: EndBug/latest-tag@latest

    - name: Publish New Release
      uses: softprops/action-gh-release@v1
      with:
        files: docs/manual/build/*.pdf
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
